# 去 DeepSeek 化 —— xcstrings 批处理（正确版）
# 事故教训：上一版把 fix() 的返回值（计数）赋给了 dict 节点，把 strings 整个写成 0。
# 本版：mutate + 计数分离；写回前强制重新解析验证。
import io, json, sys
sys.stdout.reconfigure(encoding="utf-8")

ROOT = r"D:\xiaodi-push\DeepSeekHarnessMobile\Resources"

REPLACES = [
    ("新建 DeepSeek Harness", "新会话"),
    ("New DeepSeek Harness", "New Chat"),
    ("DeepSeek · 正在生成", "朱小姐 · 正在生成"),
    ("DeepSeek · Generating", "Zhu Xiaojie · Generating"),
    ("DeepSeek Harness 预览版", "朱小姐 预览版"),
    ("DeepSeek Harness Preview", "Zhu Xiaojie Preview"),
    ("由 DeepSeek Harness 提供的 Agent 预设。", "电脑端提供的 Agent 预设。"),
    ("An agent preset provided by DeepSeek Harness.", "An agent preset provided by your connected computer."),
    ("尚未连接到 DeepSeek Harness。请点击主页右上角的 🔑 按钮，扫描配对二维码或手动输入 Token 进行连接。",
     "尚未连接到电脑。请打开左划栏 → 配对设备，扫码或手动输入地址进行连接。"),
    ("Not connected to DeepSeek Harness. Tap the 🔑 button at the top-right of Home to scan the pairing QR code or enter a token manually.",
     "Not connected to your computer. Open the side drawer, then scan the pairing QR code or enter the address manually."),
    ("当前 Mobile Gateway 不支持图片，请升级并重启 dsh web。", "当前网关不支持图片，请升级电脑端。"),
    ("The current Mobile Gateway doesn’t support images. Upgrade and restart dsh web.",
     "The current gateway doesn’t support images. Upgrade the desktop app."),
    ("请先在设置中连接 DeepSeek Harness", "请先在设置中连接电脑"),
    ("Connect to DeepSeek Harness in Settings first", "Connect to your computer in Settings first"),
    ("请先连接 DeepSeek Harness", "请先连接电脑"),
    ("Connect to DeepSeek Harness first", "Connect to your computer first"),
    ("Base64URL 解码后的内容不是有效的 DeepSeek Harness 配对 JSON。",
     "Base64URL 解码后的内容不是有效的配对数据。"),
    ("The Base64URL-decoded payload isn’t valid DeepSeek Harness pairing JSON.",
     "The Base64URL-decoded payload isn’t valid pairing data."),
    ("未获得相机权限。请在系统设置中允许 DeepSeek Harness 使用相机后重试。",
     "未获得相机权限。请在系统设置中允许朱小姐使用相机后重试。"),
    ("Camera access wasn’t granted. Allow DeepSeek Harness to use the camera in system settings, then try again.",
     "Camera access wasn’t granted. Allow Zhu Xiaojie to use the camera in system settings, then try again."),
    ("相机权限不可用。请在系统设置中允许 DeepSeek Harness 使用相机后重试。",
     "相机权限不可用。请在系统设置中允许朱小姐使用相机后重试。"),
    ("Camera access is unavailable. Allow DeepSeek Harness to use the camera in system settings, then try again.",
     "Camera access is unavailable. Allow Zhu Xiaojie to use the camera in system settings, then try again."),
    ("DshMobile uses the camera to scan device pairing QR codes generated by the DeepSeek Harness WebUI.",
     "Zhu Xiaojie uses the camera to take photos and to scan pairing QR codes generated by the desktop app."),
    ("允许 DshMobile 扫描 DeepSeek Harness WebUI 生成的设备配对二维码。",
     "拍照发给朱小姐，或扫描电脑端生成的配对二维码。"),
    ("Connects to the DeepSeek Harness Mobile Gateway on your local network.",
     "Connects to the Zhu Xiaojie desktop gateway over your network."),
    ("连接局域网中的 DeepSeek Harness Mobile Gateway。", "连接朱小姐的电脑端网关（同一网络或远程虚拟网络）。"),
    ("While an Agent is running, DshMobile uses low-accuracy background location to keep the task connected. Location data is never stored or uploaded.",
     "While an Agent is running, Zhu Xiaojie uses low-accuracy background location to keep the task connected. Location data is never stored or uploaded."),
    ("While an Agent is running, DshMobile uses low-accuracy location to keep the task connected. Location data is never stored or uploaded.",
     "While an Agent is running, Zhu Xiaojie uses low-accuracy location to keep the task connected. Location data is never stored or uploaded."),
    ("把按住麦克风录到的语音转成文字，发送给 DeepSeek Harness。识别优先使用设备端能力。",
     "把按住麦克风录到的语音转成文字，发送给朱小姐。识别优先使用设备端能力。"),
    ("While an Agent is running, Zhu Xiaojie", "While an Agent is running, Zhu Xiaojie"),  # 幂等占位
]

def apply_str(s: str):
    count = 0
    for a, b in REPLACES:
        if a in s:
            count += s.count(a)
            s = s.replace(a, b)
    return s, count

def fix(v):
    """就地修正；返回替换计数。dict/list 递归，str 替换。"""
    total = 0
    if isinstance(v, dict):
        out = {}
        for k, val in v.items():
            nk, c1 = apply_str(k)
            nv, c2 = fix(val)
            out[nk] = nv
            total += c1 + c2
        v.clear()
        v.update(out)
        return total
    if isinstance(v, list):
        for i, item in enumerate(v):
            nv, c = fix(item)
            v[i] = nv
            total += c
        return total
    if isinstance(v, str):
        nv, c = apply_str(v)
        if c:
            # 调用方负责把 nv 放回；字符串叶子由父级处理 —— 这里直接返回
            return nv
        return v
    return v

def fix_root(data):
    """正确的根遍历：返回 (data, count)"""
    count = 0
    if isinstance(data, dict):
        out = {}
        for k, val in data.items():
            nk, c1 = apply_str(k)
            if isinstance(val, (dict, list)):
                c2, val2 = _walk(val)
            elif isinstance(val, str):
                val2, c2 = apply_str(val)
            else:
                val2, c2 = val, 0
            out[nk] = val2
            count += c1 + c2
        data.clear()
        data.update(out)
        return data, count
    return data, 0

def _walk(v):
    """返回 (count, mutated_value)"""
    total = 0
    if isinstance(v, dict):
        out = {}
        for k, val in v.items():
            nk, c1 = apply_str(k)
            c2, nv = _walk(val)
            out[nk] = nv
            total += c1 + c2
        v.clear()
        v.update(out)
        return total, v
    if isinstance(v, list):
        for i, item in enumerate(v):
            c, nv = _walk(item)
            v[i] = nv
            total += c
        return total, v
    if isinstance(v, str):
        nv, c = apply_str(v)
        return c, nv
    return 0, v

ok = True
for name in ("InfoPlist.xcstrings", "Localizable.xcstrings"):
    p = ROOT + "\\" + name
    with io.open(p, encoding="utf-8") as f:
        data = json.load(f)
    before_entries = len(data.get("strings", {}))
    _, n = fix_root(data)
    # 写回前验证：重新 dumps->loads
    blob = json.dumps(data, ensure_ascii=False, indent=2)
    reloaded = json.loads(blob)
    after_entries = len(reloaded.get("strings", {}))
    if after_entries != before_entries:
        print(f"✗ {name}: 条目数变化 {before_entries}->{after_entries} —— 不写盘！")
        ok = False
        continue
    with io.open(p, "w", encoding="utf-8") as f:
        f.write(blob + "\n")
    # 残留统计
    residual = blob.count("DeepSeek")
    print(f"✓ {name}: 替换 {n} 处，条目 {after_entries} 不变，残留 DeepSeek={residual}")

print("RESULT=" + ("PASS" if ok else "FAIL"))
